### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by Andrews54757** [LegitSoulja/OgarConsole#2]
Never tested it but it looks awesome!

**Comment by Andrews54757** [comment]
I was thinking i should add something like this in the future, probably will but not using your code. I am going to make it advanced like pocket mine to install plugins and stuff

**Comment by Andrews54757** [comment]
I didn't add it before because I was afraid that people might try hacking ogarul servers. I told people to use SSH instead. but in the future, after I figure out encryption, I might take a try

**Comment by LegitSoulja** [comment]
Well, that for me isn't my problem. My Hub is set up with servers, and administrators. Only admins can access OgarConsole. OgarConsole can execute cmd commands, but they don't execute cmd commands, but instead only execute Ogar commands only.

**Comment by LegitSoulja** [comment]
This is a little small plugin/addons that included a console for the running server. I was planning on hosting Ogar servers in the future and this was my plan of allowing the people who purchased a server maintain it server from a actual console like form. OgarConsole is very basic and easy to setup. Right now OgarConsole is in beta, and the code isn't the final release. I will be re-developing OgarConsole entirely with more functionalities.

**Comment by LegitSoulja** [comment]
I'm just now learning nodejs and how it works, and after I understand how Ogar works entirely then I'll be re-developing OgarConsole.

**Comment by LegitSoulja** [comment]
.. Yea, um check out my new features.

**Comment by LegitSoulja** [comment]
> https://github.com/LegitSoulja/OgarConsole/issues/7#issuecomment-216086983

@Andrews54757 Like this? Is that the type of security you was worried about? There's plenty of ways to secure the console. My methods are origin matching, and password login method.

**Comment by Andrews54757** [comment]
I still recommend ssh and tmux, these are much securer

**Comment by Andrews54757** [comment]
also allows for restarting the server

**Comment by LegitSoulja** [comment]
Yikes.. My method of my Origin was a no brainer. It doesn't even works. Well it does, but it only returns the local public ip address, and not the domain. I built it not knowing about iframe use, and I built the system going by direct connect to them will object the host ip address to determine if localhost, or a domain. Well if you want it on a domain youll have to have the client on the website to connect to the server instead of using an iframe to connect to the console because connecting from iframe on a domain will only return back the server local public ip address. Do you know a work around this? This is a security risk with iframe usage, or do you know a way of blocking iframe use? Capture the local ip and if it returns back the same will result into an iframe usage, but is that a good way of doing it? 

@Andrews54757

**Comment by Andrews54757** [comment]
my brain is dead now, need to do work, thats why, try to research on google
